from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import matplotlib.pyplot as plt 
import datetime
import sys

sys.path.append('../DataBase/')
from db import Management

class Ui_workHoursAnalysis(object):

    def __init__(self):
        self.database = Management()
        self.data = self.database.returnData()
        self.analyse()

    def setupUi(self, workHoursAnalysis):
        workHoursAnalysis.setObjectName("workHoursAnalysis")
        workHoursAnalysis.resize(800, 603)

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        workHoursAnalysis.setPalette(palette)

        self.centralwidget = QtWidgets.QWidget(workHoursAnalysis)
        self.centralwidget.setObjectName("centralwidget")
        self.graph = QtWidgets.QLabel(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(170, 140, 461, 400))
        self.graph.setText("")
        self.graph.setTextFormat(QtCore.Qt.PlainText)
        self.graph.setPixmap(QtGui.QPixmap("plot.png"))
        self.graph.setScaledContents(True)
        self.graph.setObjectName("graph")

        self.weekDate = QtWidgets.QLabel(self.centralwidget)
        self.weekDate.setGeometry(QtCore.QRect(210, 540, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.weekDate.setFont(font)
        self.weekDate.setAlignment(QtCore.Qt.AlignCenter)
        self.weekDate.setObjectName("weekDate")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 781, 111))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.date = QtWidgets.QLabel(self.frame)
        self.date.setGeometry(QtCore.QRect(10, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.date.setFont(font)
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")

        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(10, 60, 201, 41))
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setObjectName("dateEdit")
        today = datetime.date.today()
        self.dateEdit.setDate(today)
        self.workEdit = QtWidgets.QSpinBox(self.frame)
        self.workEdit.setGeometry(QtCore.QRect(230, 60, 181, 41))
        self.workEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.workEdit.setObjectName("workEdit")
        self.wasteEdit = QtWidgets.QSpinBox(self.frame)
        self.wasteEdit.setGeometry(QtCore.QRect(430, 60, 181, 41))
        self.wasteEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.wasteEdit.setObjectName("wasteEdit")

        self.work = QtWidgets.QLabel(self.frame)
        self.work.setGeometry(QtCore.QRect(230, 20, 181, 31))
        self.work.setAlignment(QtCore.Qt.AlignCenter)
        self.work.setObjectName("work")
        self.waste = QtWidgets.QLabel(self.frame)
        self.waste.setGeometry(QtCore.QRect(430, 20, 181, 31))
        self.waste.setAlignment(QtCore.Qt.AlignCenter)
        self.waste.setObjectName("waste")

        self.addButton = QtWidgets.QPushButton(self.frame)
        self.addButton.setGeometry(QtCore.QRect(650, 10, 121, 41))
        self.addButton.setObjectName("addButton")
        self.updateButton = QtWidgets.QPushButton(self.frame)
        self.updateButton.setGeometry(QtCore.QRect(650, 60, 121, 41))
        self.updateButton.setObjectName("updateButton")

        self.preWeek = QtWidgets.QPushButton(self.centralwidget)
        self.preWeek.setGeometry(QtCore.QRect(170, 540, 41, 31))
        self.preWeek.setObjectName("preWeek")
        self.nextWeek = QtWidgets.QPushButton(self.centralwidget)
        self.nextWeek.setGeometry(QtCore.QRect(590, 540, 41, 31))
        self.nextWeek.setObjectName("nextWeek")

        workHoursAnalysis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(workHoursAnalysis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        workHoursAnalysis.setMenuBar(self.menubar)

        self.retranslateUi(workHoursAnalysis)
        QtCore.QMetaObject.connectSlotsByName(workHoursAnalysis)

        self.addButton.clicked.connect(lambda: self.add_clicked(self.dateEdit.date(), self.workEdit.value(), self.wasteEdit.value()))
        self.updateButton.clicked.connect(lambda: self.update_clicked(self.dateEdit.date(), self.workEdit.value(), self.wasteEdit.value()))
        self.preWeek.clicked.connect(self.pre_clicked)
        self.nextWeek.clicked.connect(self.next_clicked)

    def retranslateUi(self, workHoursAnalysis):
        _translate = QtCore.QCoreApplication.translate
        workHoursAnalysis.setWindowTitle(_translate("workHoursAnalysis", "Work Hour Analysis"))
        
        self.weekDate.setText(_translate("workHoursAnalysis", "01/01/2021 - 07/01/2021"))
        self.date.setText(_translate("workHoursAnalysis", "Date"))
        self.work.setText(_translate("workHoursAnalysis", "Work Hours"))
        self.waste.setText(_translate("workHoursAnalysis", "Waste Hours"))
        self.addButton.setText(_translate("workHoursAnalysis", "Add"))
        self.updateButton.setText(_translate("workHoursAnalysis", "Update"))
        self.preWeek.setText(_translate("workHoursAnalysis", "<"))
        self.nextWeek.setText(_translate("workHoursAnalysis", ">"))

    def add_clicked(self, dateVal, workVal, wasteVal):
        dateVal = datetime.datetime(dateVal.year(), dateVal.month(), dateVal.day())
        self.database.insertData([str(dateVal.strftime('%Y-%m-%d')), workVal, wasteVal])
        print('ADD', str(dateVal), workVal, wasteVal)
        self.update()
    
    def update_clicked(self, dateVal, workVal, wasteVal):
        print('UPDATE', str(dateVal), workVal, wasteVal)
    
    def pre_clicked(self):
        """Plot of previous week"""
        dateRange = self.weekDate.text().split(' ')
        lDate = datetime.datetime.strptime(dateRange[0], '%d/%m/%Y') - datetime.timedelta(days=7)
        rDate = datetime.datetime.strptime(dateRange[-1], '%d/%m/%Y') - datetime.timedelta(days=7)
        self.weekDate.setText(lDate.strftime('%d/%m/%Y') + ' - ' + rDate.strftime('%d/%m/%Y'))
    
    def next_clicked(self):
        """Plot of previous week"""
        dateRange = self.weekDate.text().split(' ')
        lDate = datetime.datetime.strptime(dateRange[0], '%d/%m/%Y') + datetime.timedelta(days=7)
        rDate = datetime.datetime.strptime(dateRange[-1], '%d/%m/%Y') + datetime.timedelta(days=7)
        self.weekDate.setText(lDate.strftime('%d/%m/%Y') + ' - ' + rDate.strftime('%d/%m/%Y'))

    def update(self):
        """Update the plot with every addition or updation"""
        self.data = self.database.returnData()
        print(self.data)
        self.analyse()
        self.graph.setPixmap(QtGui.QPixmap("plot.png"))

    def analyse(self):
        """Plotting the data that was extracted from the database"""
        data = np.array(self.data[-7:]).T
        X = np.array(data[1:3]).astype('float64')

        plt.plot(data[0], X[0], X[1])
        plt.savefig('plot.png')
        plt.clf()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    workHoursAnalysis = QtWidgets.QMainWindow()
    ui = Ui_workHoursAnalysis()
    ui.setupUi(workHoursAnalysis)
    workHoursAnalysis.show()
    sys.exit(app.exec_())
